import { useState } from 'react';
import { BedDouble, Ship, CheckCircle2, Mail, MapPin } from 'lucide-react';
import PageBanner from './PageBanner';

const servicePages = {
  hotels: { eyebrow: 'Stay ideas', title: 'Find a stay that suits your Australia trip', description: 'Explore ideas for city stays, beach escapes, road trips and nature breaks.', icon: BedDouble, cta: 'Request stay ideas', points: ['Options for different budgets and travel styles', 'Flexible dates and room preferences', 'Trip planning support'] },
  ferry: { eyebrow: 'Travel planning', title: 'Plan your Australian journey with ease', description: 'Build a route that connects your preferred destinations and travel style.', icon: Ship, cta: 'Plan my trip', points: ['Route and transfer suggestions', 'Help planning onward travel', 'Simple enquiry support'] },
};

const legalPages = {
  privacy: {
    eyebrow: 'Privacy Policy',
    title: 'Your privacy matters to us',
    description: 'How thetraveloz collects, uses, discloses, and protects your personal information.',
    sections: [
      { heading: 'Introduction', paragraphs: ['At thetraveloz, your privacy is important to us. This Privacy Policy explains how we collect, use, disclose, and protect your personal information when you visit our website thetraveloz.com or use our travel booking services.', 'By using our website and services, you consent to the collection and use of your information as described in this policy.'] },
      { heading: 'Information We Collect', paragraphs: ['thetraveloz may collect the following types of information:'], items: ['Personal Information: Name, email address, phone number, billing address, and payment details when you make a booking.', 'Travel Information: Passport details, frequent flyer numbers, travel preferences, and special requests.', 'Technical Information: IP address, browser type, device information, and cookies (see our Cookies Policy).', 'Usage Information: Pages visited, search queries, and interactions with our website.'] },
      { heading: 'How We Use Your Information', paragraphs: ['thetraveloz uses your information to:'], items: ['Process and confirm your flight, hotel, and car rental bookings', 'Communicate with you about your reservations', 'Provide customer support and respond to inquiries', 'Personalize your travel recommendations and offers', 'Improve our website functionality and user experience', 'Comply with legal and regulatory requirements'] },
      { heading: 'Sharing Your Information', paragraphs: ['thetraveloz does not sell your personal information. We may share your information with:'], items: ['Airlines & Travel Suppliers: To complete your travel bookings.', 'Payment Processors: To securely handle transactions.', 'Service Providers: Third parties that assist with website operations and customer support.', 'Legal Authorities: When required by law or to protect our rights.'] },
      { heading: 'Data Security', paragraphs: ['thetraveloz implements industry-standard security measures to protect your personal information from unauthorized access, alteration, disclosure, or destruction. These include:'], items: ['SSL encryption for data transmission', 'Secure payment gateways', 'Regular security audits and updates', 'Restricted access to personal information'], after: 'While we strive to protect your data, no method of transmission over the internet is 100% secure.' },
      { heading: 'Your Rights', paragraphs: ['Depending on your location, you may have the following rights:'], items: ['Access the personal information we hold about you', 'Request correction of inaccurate or incomplete information', 'Request deletion of your personal information', 'Opt-out of marketing communications', 'Object to certain data processing activities'], after: 'To exercise these rights, please contact us using the information below.' },
      { heading: 'Data Retention', paragraphs: ['thetraveloz retains your personal information only as long as necessary to fulfill the purposes outlined in this policy, comply with legal obligations, resolve disputes, and enforce our agreements.'] },
      { heading: "Children's Privacy", paragraphs: ['Our services are not directed to individuals under the age of 18. thetraveloz does not knowingly collect personal information from children. If we become aware that we have collected information from a child, we will take steps to delete it promptly.'] },
      { heading: 'Updates to This Policy', paragraphs: ['thetraveloz may update this Privacy Policy from time to time to reflect changes in legal requirements, our practices, or industry standards. Any updates will be posted on this page with a revised "Last Updated" date. We encourage you to review this policy periodically.'] },
      { heading: 'Contact Information', paragraphs: ['If you have any questions about this Privacy Policy or how we handle your personal information, please contact us:'], items: ['Email: info@thetraveloz.com', 'Phone: x-xxx-xxx-xxxx', 'Address: 13217 Juliet Way, Frisco, TX 75035, USA'] },
      { heading: 'Disclaimer', paragraphs: ['thetraveloz is committed to protecting your privacy and ensuring transparency in our data collection practices. For more information about how we use cookies, please review our Cookies Policy at thetraveloz.com/cookie-policy.'] },
    ],
  },
  terms: {
    eyebrow: 'Terms & conditions',
    title: 'Clear terms for better travel',
    description: 'The basic terms that apply when you request or purchase travel services through thetraveloz.',
    sections: [
      { heading: 'Introduction', paragraphs: ['Welcome to thetraveloz. These Terms and Conditions govern your use of our website thetraveloz.com and the travel booking services we provide. By accessing or using our website, you agree to be bound by these terms.', 'If you do not agree with any part of these terms, please do not use our website or services.'] },
      { heading: 'Booking Services', paragraphs: ['thetraveloz acts as an independent travel agency facilitating bookings for flights, hotels, car rentals, and vacation packages. We do not operate airlines, hotels, or other travel suppliers. All bookings are subject to the terms and conditions of the respective service providers.'], items: ['You are responsible for providing accurate information', 'You have read and agree to the supplier\'s terms', 'thetraveloz is not liable for supplier service failures', 'Additional fees may apply for changes or cancellations'] },
      { heading: 'User Responsibilities', paragraphs: ['As a user of thetraveloz\'s services, you agree to:'], items: ['Provide accurate, complete, and current information', 'Maintain the confidentiality of your account credentials', 'Review all booking details before confirmation', 'Comply with all applicable laws and regulations', 'Ensure you have valid travel documents (passport, visa, etc.)', 'Arrive at the airport with sufficient time before departure'] },
      { heading: 'Pricing and Payments', paragraphs: ['All prices displayed on thetraveloz are subject to change without notice. Final prices are confirmed at the time of booking. Prices include applicable taxes and fees unless stated otherwise.'], items: ['Payments are processed through secure payment gateways', 'We accept major credit cards (Visa, MasterCard, Amex, Discover)', 'Additional service fees may apply for certain bookings', 'Currency conversion fees may apply for international bookings'] },
      { heading: 'Cancellations and Changes', paragraphs: ['Cancellation and change policies vary by airline, hotel, or travel supplier. Please review the specific terms for your booking. In general:'], items: ['Some fares are non-refundable and non-changeable', 'Cancellation fees may apply based on the supplier\'s policy', 'thetraveloz service fees are non-refundable after booking', 'Changes may be subject to fare differences', 'No-show penalties apply for missed flights without prior cancellation'], after: 'For cancellations or changes, contact thetraveloz customer support as soon as possible.' },
      { heading: 'Refunds', paragraphs: ['Refunds are processed according to the supplier\'s refund policy. thetraveloz will assist with refund requests but cannot guarantee approval. Eligible refunds will be credited to the original payment method within 7-20 business days depending on the supplier.'] },
      { heading: 'Intellectual Property', paragraphs: ['All content on the thetraveloz website, including text, graphics, logos, images, and software, is the property of thetraveloz or its content suppliers and is protected by copyright and intellectual property laws. You may not reproduce, distribute, or create derivative works without express written permission.'] },
      { heading: 'Limitation of Liability', paragraphs: ['To the maximum extent permitted by law, thetraveloz shall not be liable for:'], items: ['Any direct, indirect, incidental, or consequential damages', 'Loss of profits, data, or business opportunities', 'Delays, cancellations, or service failures by airlines or suppliers', 'Personal injury, illness, or death during travel', 'Loss or damage to baggage or personal belongings'], after: 'Our total liability for any claim arising from your use of our services is limited to the amount you paid for the booking.' },
      { heading: 'Indemnification', paragraphs: ['You agree to indemnify and hold thetraveloz harmless from any claims, damages, losses, liabilities, costs, or expenses arising from your use of our website, violation of these terms, or infringement of any third-party rights.'] },
      { heading: 'Governing Law', paragraphs: ['These Terms and Conditions shall be governed by and construed in accordance with the laws of the State of New Hampshire, United States, without regard to its conflict of law provisions. Any legal action arising from these terms shall be brought exclusively in the courts of Portsmouth, New Hampshire.'] },
      { heading: 'Changes to Terms', paragraphs: ['thetraveloz reserves the right to modify these Terms and Conditions at any time. Changes will be effective immediately upon posting on this page. Your continued use of our website constitutes acceptance of the modified terms.'] },
      { heading: 'Contact Information', paragraphs: ['If you have any questions about these Terms and Conditions, please contact us:'], items: ['Email: info@thetraveloz.com', 'Phone: x-xxx-xxx-xxxx', 'Address: 13217 Juliet Way, Frisco, TX 75035, USA'] },
      { heading: 'Disclaimer', paragraphs: ['thetraveloz provides travel booking services as an independent agent. We are not responsible for the actions, errors, omissions, representations, or warranties of any airlines, hotels, or other travel suppliers. Your travel is at your own risk, and we recommend purchasing travel insurance for protection.'] },
    ],
  },
  ccpa: {
    eyebrow: 'CCPA',
    title: 'Your California privacy rights',
    description: 'Information for California residents about personal information, privacy choices, and the rights available under California law.',
    sections: [
      { heading: 'Introduction', paragraphs: ['This California Consumer Privacy Act ("CCPA") Notice forms part of thetraveloz\'s Privacy Policy and applies exclusively to California residents ("Consumers," "you," or "your") as defined under applicable California privacy laws.', 'Unless otherwise stated, terms used in this Notice carry the same meaning as provided in our Privacy Policy or under the CCPA. In the event of any inconsistency between this Notice and our Privacy Policy, this Notice shall govern solely with respect to California residents and their personal information.', 'This Notice explains your rights regarding the collection, use, disclosure, and sharing of personal information by thetraveloz.'] },
      { heading: 'About thetraveloz', paragraphs: ['thetraveloz.com is an independent travel agency offering booking assistance for flights, hotels, vacation packages, and other travel-related services.', 'We are not directly affiliated with airlines or travel suppliers unless explicitly stated. All bookings, fares, and pricing remain subject to availability and supplier approval.', 'thetraveloz.com is owned and operated by Aadi Travel LLC.'] },
      { heading: 'Right to Know What Personal Information We Collect', paragraphs: ['California residents have the right to request information regarding the personal information thetraveloz has collected about them during the previous 12 months.'], items: ['The categories of personal information collected', 'The sources from which information was collected', 'The business purpose for collecting the data', 'How the information has been used or disclosed', 'The categories of third parties receiving the data'], after: 'California residents may submit up to two verified requests within a 12-month period.' },
      { heading: 'Right to Request Deletion', paragraphs: ['You have the right to request deletion of personal information collected by thetraveloz, subject to specific legal and operational exceptions permitted under California law.', 'After verifying your identity and determining that no legal obligation requires us to retain the information, we will delete your data from our systems.'], items: ['Complete bookings or requested transactions', 'Detect fraud or security incidents', 'Comply with legal obligations', 'Resolve disputes and enforce agreements', 'Maintain records of privacy-related requests'] },
      { heading: 'Right to Opt Out of “Sale” or Sharing of Personal Information', paragraphs: ['California residents have the right to opt out of the “sale” or sharing of personal information as defined under the CCPA.', 'thetraveloz may share certain categories of information with advertising, analytics, or marketing service providers in a manner that may be considered a “sale” or “sharing” under California privacy laws.', 'This does not include sensitive financial information or data shared solely for operational and booking purposes.'], after: 'To exercise your right to opt out, California users may use the “Do Not Sell or Share My Personal Information” link available on our website.' },
      { heading: 'How to Exercise Your Rights', paragraphs: ['California residents may submit requests regarding access, deletion, or privacy rights using the following methods:'], items: ['Email: info@thetraveloz.com', 'Through the “Do Not Sell or Share My Personal Information” link available on our website'], after: 'We may need to verify your identity before processing certain requests in order to protect your personal information.' },
      { heading: 'Non-Discrimination', paragraphs: ['thetraveloz will not discriminate against California residents for exercising any rights granted under the CCPA.'], items: ['Denying services or bookings', 'Charging different prices or fees', 'Providing a different level of service quality', 'Imposing penalties for privacy requests'] },
      { heading: 'Changes to This Notice', paragraphs: ['thetraveloz reserves the right to update or modify this CCPA Notice at any time. Changes will become effective immediately upon posting on this page.', 'Continued use of our website and services after updates constitutes acceptance of the revised Notice.'] },
      { heading: 'Contact Information', paragraphs: ['If you have questions regarding this CCPA Notice or wish to exercise your California privacy rights, please contact us:'], items: ['Email: info@thetraveloz.com', 'Phone: x-xxx-xxx-xxxx', 'Address: 13217 Juliet Way, Frisco, TX 75035, USA'] },
      { heading: 'Disclaimer', paragraphs: ['thetraveloz provides travel booking assistance as an independent travel agency. We are not responsible for the actions, delays, errors, or omissions of airlines, hotels, or third-party travel providers.', 'Your use of our website and services is at your own discretion, and we recommend reviewing all supplier policies carefully before completing any booking.'] },
    ],
  },
  gdpr: {
    eyebrow: 'GDPR',
    title: 'Your data protection rights',
    description: 'How we respect the privacy rights of people in the European Economic Area and the United Kingdom.',
    sections: [
      { heading: 'Introduction', paragraphs: ['This General Data Protection Regulation ("GDPR") Privacy Notice supplements thetraveloz\'s Privacy Policy and applies specifically to users located within the European Economic Area ("EEA") and the United Kingdom ("UK").', 'This Notice explains how thetraveloz collects, stores, processes, and protects your personal information when you access our website thetraveloz.com and use our travel-related services.', 'By using our website and services, you acknowledge and agree to the practices described in this GDPR Privacy Notice.'] },
      { heading: 'Who We Are', paragraphs: ['thetraveloz.com is an independent travel agency offering booking assistance for flights, hotels, car rentals, vacation packages, and related travel services.', 'We are not directly affiliated with airlines, hotel brands, or travel suppliers unless otherwise stated. All prices and fares are subject to availability and may change until ticketed.', 'thetraveloz.com is owned and operated by Aadi Travel LLC.'] },
      { heading: 'Data Controller', paragraphs: ['thetraveloz acts as the data controller for personal information collected through our website, customer support channels, and travel booking services.'], items: ['Book or inquire about travel services', 'Contact customer support', 'Subscribe to promotional communications', 'Interact with our website or advertisements', 'Submit forms or participate in surveys'] },
      { heading: 'Information We Collect', paragraphs: ['Depending on how you interact with our services, we may collect personal and technical information.'], items: ['Full name and contact details', 'Email address and phone number', 'Billing and payment information', 'Travel itinerary and booking details', 'Passport or identification details if required', 'IP address and browser/device information', 'Website usage and analytics information'] },
      { heading: 'How We Use Your Information', paragraphs: ['We process your personal information for legitimate business and operational purposes.'], items: ['Process and manage travel bookings', 'Provide customer service and booking assistance', 'Send confirmations and important travel updates', 'Improve website functionality and user experience', 'Prevent fraud and unauthorized transactions', 'Comply with legal and regulatory obligations', 'Send promotional offers where permitted by law'] },
      { heading: 'International Data Transfers', paragraphs: ['Your personal information may be transferred and processed outside the EEA or UK, including in the United States, in order to provide requested travel services.', 'Where required, thetraveloz implements appropriate safeguards such as Standard Contractual Clauses (SCCs) and secure processing agreements with third-party providers.'] },
      { heading: 'Data Retention', paragraphs: ['We retain personal information only for as long as necessary to fulfill business, legal, and operational requirements.'], items: ['Managing and completing bookings', 'Providing customer support', 'Preventing fraud and abuse', 'Meeting accounting and legal obligations', 'Resolving disputes or chargebacks'] },
      { heading: 'How We Protect Your Information', paragraphs: ['thetraveloz maintains commercially reasonable technical and organizational safeguards to help protect your information from unauthorized access, misuse, or disclosure.'], items: ['SSL-secured website encryption', 'Secure payment gateways', 'Restricted internal access controls', 'Fraud monitoring systems', 'PCI-compliant payment processing where applicable'] },
      { heading: 'Sharing of Information', paragraphs: ['We may share your personal information with trusted third parties when necessary to provide our services.'], items: ['Airlines and travel suppliers', 'Hotels and transportation providers', 'Payment processors', 'Analytics and hosting providers', 'Customer support partners', 'Government or legal authorities where required by law'] },
      { heading: 'Your GDPR Rights', paragraphs: ['If you are located in the EEA or UK, you have important rights regarding your personal information.'], items: ['Request access to your personal data', 'Correct inaccurate information', 'Request deletion of your information', 'Restrict or object to certain processing activities', 'Withdraw consent where applicable', 'Request portability of your data', 'Opt out of direct marketing communications'], after: 'To exercise your rights, please contact our support team using the information below.' },
      { heading: 'Children’s Privacy', paragraphs: ['thetraveloz does not knowingly collect personal information from individuals under the age of 18. If we become aware that such information has been collected unintentionally, we will promptly remove it from our systems.'] },
      { heading: 'Limitation of Liability', paragraphs: ['While we work hard to protect your information, no online system or internet transmission can be guaranteed to be 100% secure.', 'thetraveloz shall not be responsible for unauthorized access caused by factors beyond our reasonable control.'] },
      { heading: 'Changes to This Notice', paragraphs: ['thetraveloz reserves the right to update or modify this GDPR Privacy Notice at any time. Changes will become effective immediately upon posting on this page.', 'Continued use of our website and services after updates constitutes acceptance of the revised Notice.'] },
      { heading: 'Contact Information', paragraphs: ['If you have questions regarding this GDPR Privacy Notice or wish to exercise your privacy rights, please contact us:'], items: ['Email: info@thetraveloz.com', 'Phone: x-xxx-xxx-xxxx', 'Address: 13217 Juliet Way, Frisco, TX 75035, USA'] },
      { heading: 'Disclaimer', paragraphs: ['thetraveloz provides travel booking assistance as an independent travel agency. We are not responsible for the actions, omissions, delays, or service interruptions caused by airlines, hotels, or third-party travel providers.', 'Your use of our website and services is at your own discretion, and we recommend reviewing all supplier policies before booking.'] },
    ],
  },
  advertiser: {
    eyebrow: 'Advertiser policy',
    title: 'Advertising built on trust',
    description: 'How thetraveloz presents promotional content, travel offers, and sponsored listings transparently and responsibly.',
    sections: [
      { heading: 'Our Commitment to Transparency', paragraphs: ['At thetraveloz, transparency and trust are important parts of how we serve travelers. This Advertiser Disclosure explains how promotional content, travel offers, sponsored listings, and special deals may be displayed on thetraveloz.com.', 'Our goal is to help travelers make informed booking decisions through clear communication, fair pricing information, and responsible advertising practices.'] },
      { heading: 'Accurate Promotion of Travel Offers', paragraphs: ['Any deal, discount, fare, or promotional travel offer shown on thetraveloz is intended to reflect genuine booking opportunities available at the time of display.', 'We make reasonable efforts to communicate important pricing details, inclusions, limitations, and booking conditions before a customer completes a reservation.'] },
      { heading: 'Clear Terms & Conditions', paragraphs: ['Promotional offers may include specific terms, restrictions, eligibility requirements, travel dates, cancellation rules, or supplier conditions.', 'We encourage all customers to review the final booking details, fare rules, and supplier terms carefully before confirming any travel purchase.'] },
      { heading: 'Clear Distinction Between Offers', paragraphs: ['thetraveloz may display standard fares, discounted offers, limited-time promotions, or sponsored travel listings. We work to present these offers in a way that helps users understand the difference between regular pricing and promotional opportunities.', 'Sponsored or promotional placements do not guarantee that an offer is the lowest available price for every traveler or itinerary.'] },
      { heading: 'Real-Time Pricing & Availability', paragraphs: ['Flight prices, hotel rates, package pricing, and seat availability may change at any time due to supplier inventory, airline rules, demand, and real-time market conditions.', 'While thetraveloz works to display updated pricing, final fares and availability are confirmed only during the booking process before payment or ticketing.'] },
      { heading: 'Regulatory & Advertising Compliance', paragraphs: ['thetraveloz strives to follow applicable advertising laws, consumer protection standards, and responsible marketing practices.', 'Promotional content is intended to be presented in a lawful, ethical, and transparent manner.'] },
      { heading: 'Customer Privacy Protection', paragraphs: ['Your privacy matters to us. Promotional communications and advertising-related activity are handled in accordance with our Privacy Policy.', 'thetraveloz does not use customer information for unauthorized marketing purposes and works to protect personal data shared through our website and booking channels.'] },
      { heading: 'Continuous Improvement', paragraphs: ['We regularly review our advertising and promotional practices to improve clarity, accuracy, user experience, and customer trust. Customer feedback, industry standards, and best practices help us maintain responsible advertising on thetraveloz.'] },
      { heading: 'Contact Information', paragraphs: ['If you have questions about this Advertiser Disclosure, please contact thetraveloz:'], items: ['Email: info@thetraveloz.com', 'Phone: x-xxx-xxx-xxxx', 'Address: 13217 Juliet Way, Frisco, TX 75035, USA'] },
      { heading: 'Disclaimer', paragraphs: ['thetraveloz.com is owned and operated by Aadi Travel LLC. thetraveloz is an independent travel agency and is not directly affiliated with airlines, hotels, or travel suppliers unless clearly stated.', 'All fares, offers, promotions, and availability are subject to change until confirmed and ticketed.'] },
    ],
  },
  taxesFees: {
    eyebrow: 'Taxes & fees',
    title: 'Understanding taxes and fees',
    description: 'A guide to how taxes, charges, and service fees may apply to travel arrangements booked through thetraveloz.',
    sections: [
      { heading: 'Taxes and Fees Overview', paragraphs: ['thetraveloz.com is an independent travel agency offering booking assistance for flights, hotels, car rentals, and vacation packages. Taxes, fees, and service charges may vary based on route, supplier, passenger type, and booking details.', 'The information below is provided for general guidance only. Final charges will be shown during the booking process before payment is completed on thetraveloz.com.'] },
      { heading: 'Common Travel Taxes and Service Fees', paragraphs: ['The table below outlines common taxes and fees that may apply to certain itineraries and travel products.'], items: ['Security & Insurance Surcharge — Flights operated by selected international carriers — AP — $4.00 per leg', 'Alaska/Hawaii Travel Facilities Tax — Flights to or from Alaska or Hawaii — US — $10.60 one-way / $21.20 round-trip', 'U.S. Domestic Segment Fee — Each segment of a domestic U.S. flight — ZP — $4.80 per segment', 'U.S. Excise Ticket Tax — U.S. mainland travel and certain Canada/Mexico routes within eligible zones — US — 7.5% of airfare', 'Passenger Facility Charge (PFC) — Charged by selected U.S. airports for facility improvements — XF — Up to $4.50 per stop', 'U.S. September 11th Security Fee — Applied to U.S. and foreign air carrier enplanements — AY — $5.60 each way', 'U.S. International Travel Tax — Flights arriving in or departing from the U.S., Puerto Rico, or U.S. Virgin Islands — US — $21.10', 'APHIS Inspection Fee — International flights arriving into the U.S. — XA — $3.83', 'Immigration Processing Fee — International arrivals into the U.S. and territories — XY — $7.00', 'Customs Processing Fee — International entries into the U.S. — YC — $6.52', 'International Departure / Arrival Taxes — Varies by destination, government, and airport authority — Varies by itinerary', 'Airfare Booking Service Fee — Applies per traveler based on fare type and booking complexity — Up to $30.00 per person', 'Hotel Booking Service Fee — Applies per room or per night depending on booking type — Up to $35.00', 'Car Rental Booking Service Fee — Applied once per car rental transaction — $14.00'] },
      { heading: 'Additional Notes', paragraphs: ['Passenger categories may include adults, children, infants, students, seniors, and military personnel.'], items: ['Government-imposed taxes and fees may change without prior notice.', 'Service fees charged by thetraveloz for processing transactions are generally non-refundable.', 'Final pricing depends on fare availability, supplier rules, passenger details, and itinerary complexity.'] },
      { heading: 'Service Fee Exceptions', paragraphs: ['Certain bookings may involve additional service fees based on fare class, route complexity, or supplier requirements.'], items: ['Business or First Class fares — Up to $100 per passenger', 'Multi-city bookings — Up to $100 per traveler', 'Multiple airline or complex itineraries — Fees may vary by booking'] },
      { heading: 'Need Help Understanding Fees?', paragraphs: ['For current taxes, fees, and charges related to your specific travel itinerary, please review the final fare breakdown during checkout or contact thetraveloz support.'], items: ['Email: info@thetraveloz.com', 'Phone: x-xxx-xxx-xxxx', 'Address: 13217 Juliet Way, Frisco, TX 75035, USA'] },
      { heading: 'Disclaimer', paragraphs: ['thetraveloz.com is owned and operated by Aadi Travel LLC. thetraveloz provides independent travel booking assistance and is not directly affiliated with any airline, hotel, or travel supplier unless clearly stated.', 'All fares, taxes, and fees are subject to availability, supplier rules, and government regulations until ticketed or confirmed.'] },
    ],
  },
  cookies: {
    eyebrow: 'Cookie policy',
    title: 'How we use cookies',
    description: 'Information about cookies and similar technologies used on thetraveloz.com to improve your browsing experience.',
    sections: [
      { heading: 'What Are Cookies?', paragraphs: ['At thetraveloz, we use cookies and similar tracking technologies to improve your browsing experience on our website thetraveloz.com. This Cookies Policy explains what cookies are, how we use them, and how you can manage your cookie preferences.', 'Cookies are small text files that are placed on your device (computer, smartphone, or tablet) when you visit a website. They are widely used to make websites work more efficiently, enhance user experience, and provide information to website owners.', 'Cookies do not contain personal information that can identify you directly, but they help us recognize your device and remember your preferences for future visits.'] },
      { heading: 'Types of Cookies We Use', paragraphs: ['thetraveloz uses the following categories of cookies:'], items: ['Essential Cookies — Required for the website to function properly (e.g., navigation, login, form submissions).', 'Performance Cookies — Help us understand how visitors interact with our website (e.g., page visits, load times).', 'Functional Cookies — Remember your preferences (e.g., language, location) to provide enhanced features.', 'Advertising Cookies — Used to deliver relevant ads and measure campaign effectiveness.'] },
      { heading: 'How We Use Cookies', paragraphs: ['thetraveloz uses cookies to:'], items: ['Remember your login details and preferences', 'Analyze website traffic and user behavior', 'Improve website performance and loading speed', 'Personalize content and offers based on your interests', 'Enable social media sharing and interactions'] },
      { heading: 'Third-Party Cookies', paragraphs: ['We may also allow third-party service providers (such as Google Analytics, Facebook, and payment processors) to place cookies on your device to help us analyze website usage, deliver targeted advertisements, and process transactions.', 'These third parties have their own privacy policies, and thetraveloz does not control their cookie practices. We recommend reviewing their policies for more information.'] },
      { heading: 'Managing Your Cookie Preferences', paragraphs: ['You can control and manage cookies through your browser settings. Most browsers allow you to:'], items: ['View cookies stored on your device', 'Block or delete existing cookies', 'Prevent websites from setting new cookies', 'Receive notifications when cookies are set'], after: 'Please note that disabling essential cookies may affect website functionality and your user experience.' },
      { heading: 'Your Consent', paragraphs: ['By continuing to use the thetraveloz website, you consent to our use of cookies as described in this policy. If you do not agree to our use of cookies, you should adjust your browser settings or refrain from using our website.'] },
      { heading: 'Updates to This Policy', paragraphs: ['thetraveloz may update this Cookies Policy from time to time to reflect changes in technology, legal requirements, or business operations. Any updates will be posted on this page with a revised “Last Updated” date.'] },
      { heading: 'Contact Information', paragraphs: ['If you have any questions about our use of cookies or this policy, please contact us:'], items: ['Email: info@thetraveloz.com', 'Phone: x-xxx-xxx-xxxx', 'Address: 13217 Juliet Way, Frisco, TX 75035, USA'] },
      { heading: 'Disclaimer', paragraphs: ['thetraveloz is committed to protecting your privacy and ensuring transparency in our data collection practices. For more information about how we handle your personal data, please review our Privacy Policy at thetraveloz.com/privacy-policy.'] },
    ],
  },
  cancellation: {
    eyebrow: 'Cancellation policy',
    title: 'Cancelling a travel booking',
    description: 'What to expect when you need to cancel or modify travel services arranged through thetraveloz.',
    sections: [
      { heading: 'How to Cancel a Booking', paragraphs: ['At thetraveloz, we understand that travel plans may change due to unexpected circumstances. This Cancellation Policy explains how cancellations are handled, applicable charges, and the process for modifying or canceling bookings made through our website thetraveloz.com.', 'Please read this policy carefully before confirming your travel reservation. By using our services, you acknowledge and accept the terms outlined below.'], items: ['Contact our customer service team immediately at info@thetraveloz.com or by phone at x-xxx-xxx-xxxx.', 'Provide your booking reference number, full name, and details of your itinerary.', 'Our agents will review the airline or travel supplier\'s fare rules and advise you on applicable cancellation charges and refund options (if available).', 'Once you confirm the cancellation, we will process it and send you a confirmation email.'] },
      { heading: 'Airline & Supplier Rules', paragraphs: ['All cancellations are subject to the individual airline or travel supplier\'s policies. These rules determine whether your booking is refundable, partially refundable, or non-refundable. Airline-imposed penalties, reissue fees, or fare differences may apply depending on the fare type and time of cancellation.', 'Some low-cost or promotional fares are non-cancellable once issued. In such cases, credits or rebooking options may be available, depending on airline policy.'] },
      { heading: 'Cancellation Fees & Charges', paragraphs: ['thetraveloz applies a nominal service fee for processing cancellations in addition to airline or supplier charges. All fees will be disclosed before confirming your cancellation.'], items: ['Domestic Flights — Service fee up to $25 per passenger (in addition to airline penalties).', 'International Flights — Service fee up to $75 per passenger (in addition to airline penalties).', 'Airlines may charge separate fees for no-shows or last-minute cancellations.'] },
      { heading: 'Time-Sensitive Cancellations', paragraphs: ['Cancellation eligibility and refund value depend on when you cancel relative to your departure date.'], items: ['Within 24 hours of booking — Most airlines allow cancellations within 24 hours of purchase without penalty (for bookings made at least 7 days before departure).', 'After 24 hours — Standard airline and agency cancellation rules apply. Refunds may be partial or unavailable depending on the fare.', 'After departure or no-shows — No refund will be available unless otherwise specified by the airline.'] },
      { heading: 'Non-Cancellable & Non-Refundable Situations', paragraphs: ['Certain bookings are strictly non-cancellable or non-refundable as per airline or hotel policy. These include but are not limited to:'], items: ['Promotional or flash sale fares', 'Group or bulk bookings', 'Partially used flight tickets', 'Bookings involving multiple suppliers with restrictive fare rules'] },
      { heading: 'Cancellations Due to External Events', paragraphs: ['In cases where travel is disrupted by weather conditions, natural disasters, strikes, government restrictions, or other events beyond our control, cancellation and refund eligibility will be determined by the airline or service provider. thetraveloz will assist you with rebooking or claim submissions where possible.'] },
      { heading: 'Refund After Cancellation', paragraphs: ['Refunds for eligible cancellations are processed only after receiving confirmation from the airline or travel supplier. Refunds will be credited to the original form of payment within 7–14 business days (up to 20 days for international carriers).', 'All refunds are subject to validation and may exclude applicable service or processing fees. thetraveloz does not hold or delay any approved refunds intentionally.'] },
      { heading: 'Legal & Compliance', paragraphs: ['thetraveloz operates in compliance with U.S. Department of Transportation (DOT) regulations and international travel laws. All policies are designed to promote transparency, accountability, and customer protection, following Google Ads advertising standards.'] },
      { heading: 'Contact Information', paragraphs: ['For cancellations, modifications, or further assistance, please contact us:'], items: ['Email: info@thetraveloz.com', 'Phone: x-xxx-xxx-xxxx', 'Address: 13217 Juliet Way, Frisco, TX 75035, USA'] },
      { heading: 'Disclaimer', paragraphs: ['thetraveloz acts as an independent travel agency. We facilitate bookings between customers and airlines, hotels, or travel suppliers but do not control their policies or decisions regarding cancellations or refunds. All travel arrangements are subject to the terms and conditions of the respective providers.'] },
    ],
  },
  refund: {
    eyebrow: 'Refund policy',
    title: 'Refunds and travel arrangements',
    description: 'How refund requests are handled for bookings made through thetraveloz.',
    sections: [
      { heading: 'When Refunds Are Available', paragraphs: ['At thetraveloz, we strive to ensure your satisfaction with every booking. This Refund Policy explains the circumstances under which refunds may be issued, how to request a refund, and the timelines involved for bookings made through our website thetraveloz.com.', 'Please read this policy carefully before requesting a refund. All refunds are subject to the terms and conditions of the respective airline or travel supplier.'], items: ['Cancellation within 24 hours — Most airlines allow full refunds for bookings canceled within 24 hours of purchase (for bookings made at least 7 days before departure).', 'Refundable Fare Types — Some fare classes allow cancellations with partial or full refunds, minus applicable fees.', 'Schedule Changes — If the airline makes significant schedule changes, you may be eligible for a refund.', 'Flight Cancellations — If the airline cancels your flight and cannot rebook you on an alternative flight.', 'Service Issues — In cases of billing errors or services not rendered as described.'] },
      { heading: 'How to Request a Refund', paragraphs: ['To request a refund, please follow these steps:'], items: ['Contact thetraveloz customer support at info@thetraveloz.com or x-xxx-xxx-xxxx', 'Provide your booking reference number and reason for refund request', 'Our team will review airline policies and advise on eligibility', 'Submit any required documentation (if applicable)', 'Once approved, refund will be processed to original payment method'] },
      { heading: 'Refund Processing Time', paragraphs: ['Refund processing times vary depending on the airline or supplier.'], items: ['Domestic Flights — 7-14 business days after approval', 'International Flights — 14-20 business days after approval', 'Hotels & Packages — 10-15 business days after approval'], after: 'Please note that your bank or credit card issuer may take additional time to reflect the refund in your account.' },
      { heading: 'Non-Refundable Situations', paragraphs: ['Refunds are typically not available in the following situations:'], items: ['Non-refundable or promotional fare types', 'No-show for your flight without prior cancellation', 'Partial use of a round-trip ticket', 'Voluntary cancellation after 24-hour grace period (for non-refundable fares)', 'Changes in personal plans or travel preferences', 'Weather-related disruptions (airline policies vary)'] },
      { heading: 'Refund Amount & Fees', paragraphs: ['The refund amount you receive may be less than your original payment due to:'], items: ['Airline-imposed cancellation penalties', 'thetraveloz service fees (non-refundable after booking confirmation)', 'Difference between original fare and current fare (for certain changes)', 'Third-party fees (insurance, seat selection, baggage fees)'], after: 'All applicable fees will be disclosed before you confirm your cancellation and refund request.' },
      { heading: 'Partial Refunds', paragraphs: ['In some cases, partial refunds may be available even when full refunds are not. Examples include:'], items: ['Downgrading from business class to economy', 'Removing optional services (e.g., extra baggage, seat selection)', 'Using a flight credit for future travel (airline policies vary)'] },
      { heading: 'Cancellations Due to External Events', paragraphs: ['In cases where travel is disrupted by weather conditions, natural disasters, strikes, government restrictions, or other events beyond our control, refund eligibility will be determined by the airline or service provider. thetraveloz will assist you with refund requests where possible.'] },
      { heading: 'Updates to This Policy', paragraphs: ['thetraveloz may update this Refund Policy from time to time to reflect changes in legal requirements, business practices, or airline policies. Any updates will be posted on this page with a revised “Last Updated” date.'] },
      { heading: 'Contact Information', paragraphs: ['For refund requests or questions about this policy, please contact us:'], items: ['Email: info@thetraveloz.com', 'Phone: x-xxx-xxx-xxxx', 'Address: 13217 Juliet Way, Frisco, TX 75035, USA'] },
      { heading: 'Disclaimer', paragraphs: ['thetraveloz acts as an independent travel agency. Final refund decisions are made by airlines, hotels, or travel suppliers based on their individual policies. thetraveloz will assist you in the refund process but cannot guarantee refund approval beyond the terms set by the service provider.'] },
    ],
  },
};

function ContactPage() {
  const [sent, setSent] = useState(false);
  return <><PageBanner eyebrow="Contact TheTravelOz" title="Let’s plan your Australia journey" description="Share your plans and TheTravelOz will help you take the next step." /><section className="contact-page"><div className="container contact-grid"><div className="contact-details"><h2>Start your trip enquiry</h2><p>Tell us about flights, stays, destinations and the experiences you have in mind.</p><a href="mailto:hello@thetraveloz.com"><Mail className="icon-sm" /> hello@thetraveloz.com</a><span><MapPin className="icon-sm" /> Australia travel inspiration, wherever you are</span></div><form className="contact-form" onSubmit={(event) => { event.preventDefault(); setSent(true); }}>{sent ? <div className="contact-success"><CheckCircle2 className="icon-lg text-emerald" /><h2>Thank you!</h2><p>Your enquiry has been received.</p></div> : <><label>Name<input required placeholder="Your name" /></label><label>Email<input type="email" required placeholder="you@example.com" /></label><label>How can we help?<textarea required rows="5" placeholder="Tell us about your ideal Australia trip" /></label><button type="submit">Send enquiry</button></>}</form></div></section></>;
}

export default function StaticPage({ type, onOpenQuoteModal }) {
  if (type === 'contact') return <ContactPage />;
  if (legalPages[type]) { const page = legalPages[type]; return <><PageBanner {...page} /><section className="legal-page"><div className="container legal-content">{page.sections.map((section) => { const [heading, copy] = Array.isArray(section) ? section : [section.heading, null]; const paragraphs = Array.isArray(section) ? [copy] : section.paragraphs; return <article key={heading}><h2>{heading}</h2>{paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.items && <ul>{section.items.map((item) => <li key={item}>{item}</li>)}</ul>}{section.after && <p>{section.after}</p>}</article>; })}</div></section></>; }
  const page = servicePages[type]; const Icon = page.icon;
  return <><PageBanner eyebrow={page.eyebrow} title={page.title} description={page.description} /><section className="service-page"><div className="container service-panel"><div className="service-icon"><Icon className="icon-xl" /></div><div><h2>Simple planning. More time to enjoy the journey.</h2><ul>{page.points.map((point) => <li key={point}><CheckCircle2 className="icon-sm" /> {point}</li>)}</ul><button onClick={onOpenQuoteModal}>{page.cta}</button></div></div></section></>;
}


